name: roundtripper
description: another composable, Future-based library for making HTTP requests
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http_parser: ^4.0.2
  dio: ^5.1.2
  context: ^0.1.0
  logr: ^0.1.0
dev_dependencies:
  filesize: ^2.0.1
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  test: ^1.24.3
  source_gen: ^1.3.2
  build_runner: ^2.4.4
