targets:
  $default:
    builders:
      freezed:
        options:
          build_extensions:
            '{{dir}}/{{file}}.dart': '{{dir}}/__generated__/{{file}}.freezed.dart'
      source_gen|combining_builder:
        options:
          build_extensions:
            '{{dir}}/{{file}}.dart': '{{dir}}/__generated__/{{file}}.g.dart'
