name: webdav
description: webdav client
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  intl: ^0.18.1
  freezed_annotation: ^2.2.0
  xml: ^6.3.0
  context: ^0.1.0
  roundtripper: ^0.1.0
  logr: ^0.1.0
dev_dependencies:
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  test: ^1.24.3
  source_gen: ^1.3.2
  build_runner: ^2.4.4
